import {
  FileText, Scissors, Archive, ImageIcon, Image, Shuffle,
  QrCode, Lock, Type, CaseSensitive, Share2, Upload,
  Merge, Minimize2, Hash, Binary, AlignLeft,
  Palette, Clock, Calculator, Globe, Zap, FileCode, LetterText, PenTool
} from "lucide-react";

export interface FAQItem {
  question: string;
  answer: string;
}

export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: any;
  category: string;
  path: string;
  benefits?: string[];
  useCases?: string[];
  howToUse?: string[];
  faqItems?: FAQItem[];
}

export interface ToolCategory {
  id: string;
  name: string;
  description: string;
  icon: any;
  color: string;
  tools: Tool[];
}

export const categories: ToolCategory[] = [
  {
    id: "pdf",
    name: "PDF Tools",
    description: "Merge, split & compress PDFs right in your browser",
    icon: FileText,
    color: "from-red-500 to-orange-500",
    tools: [
      { id: "merge-pdf", name: "Merge PDF", description: "Combine multiple PDFs into one file instantly. Merge unlimited PDFs while maintaining original quality and formatting. Local processing ensures 100% privacy.", icon: Merge, category: "pdf", path: "/tools/merge-pdf", benefits: ["Merge unlimited PDFs instantly", "No software installation required", "Local processing ensures 100% privacy", "Free, no hidden costs"], useCases: ["Combine multiple invoices into one document", "Merge report sections for professional presentations", "Consolidate scanned documents", "Combine permits and documentation"], howToUse: ["Click 'Select Files' or drag PDFs into the upload area", "Arrange PDFs in desired order", "Preview each PDF to confirm arrangement", "Click 'Merge PDFs' button", "Download your merged PDF"], faqItems: [{ question: "Is there a file size limit?", answer: "No strict limit per file, but combined uploads should not exceed 500MB." }, { question: "Will merging affect PDF quality?", answer: "No, the merge process preserves original quality and formatting." }, { question: "Is my data secure?", answer: "Yes, all processing happens locally in your browser." }] },
      { id: "split-pdf", name: "Split PDF", description: "Extract specific pages from PDF files or split them into multiple documents. Choose which pages to extract and create separate PDFs instantly without affecting quality.", icon: Scissors, category: "pdf", path: "/tools/split-pdf", benefits: ["Extract specific pages quickly", "Create multiple PDFs from one source", "Maintain original quality", "Share only relevant sections securely", "No registration needed"], useCases: ["Extract chapters from large PDF books", "Separate different sections of reports", "Remove unwanted pages from documents", "Create smaller files for email"], howToUse: ["Upload your PDF file", "Specify page ranges to extract", "Preview selected pages", "Click 'Split PDF' to process", "Download individual PDF files"], faqItems: [{ question: "Can I extract non-consecutive pages?", answer: "Yes, select individual pages like '1, 3-5, 10' to extract non-sequential pages." }, { question: "Does splitting reduce quality?", answer: "No, splitting preserves original quality and resolution of all pages." }, { question: "What if my PDF is password protected?", answer: "You'll need to remove the password protection first before using the split tool." }] },
      { id: "compress-pdf", name: "Compress PDF", description: "Reduce PDF file size without sacrificing visual quality. Intelligently optimizes images and removes unnecessary data while maintaining readability.", icon: Minimize2, category: "pdf", path: "/tools/compress-pdf", benefits: ["Reduce file size by up to 70%", "Keep PDFs email-friendly", "Maintain professional appearance", "Fast compression in seconds", "Support for large files"], useCases: ["Compress PDFs before sending via email", "Reduce storage space requirements", "Optimize files for cloud storage", "Make documents faster to download"], howToUse: ["Upload your PDF file", "Choose compression level (Standard or High)", "Preview compression estimate", "Click 'Compress' to process", "Download your compressed PDF"], faqItems: [{ question: "Will compression affect image quality?", answer: "Minimal impact with standard compression. The algorithm prioritizes quality while reducing file size." }, { question: "How much will my PDF be reduced?", answer: "Reduction varies by file content. PDFs with high-quality images typically compress 50-70%." }, { question: "Can I use this for scanned documents?", answer: "Yes, the tool works well with scanned documents and achieves significant reductions." }] },
    ],
  },
  {
    id: "image",
    name: "Image Tools",
    description: "Compress, resize & convert images instantly",
    icon: ImageIcon,
    color: "from-green-500 to-emerald-500",
    tools: [
      { id: "image-compressor", name: "Image Compressor", description: "Reduce image file sizes while preserving quality for web and sharing. Batch process multiple files with intelligent compression.", icon: Minimize2, category: "image", path: "/tools/image-compressor", benefits: ["Reduce image size by up to 80%", "Maintain visual quality", "Batch process multiple images", "Format conversion included", "Perfect for web optimization"], useCases: ["Optimize images for blog posts", "Compress photos for social media", "Reduce attachment sizes for email", "Create thumbnails and previews"], howToUse: ["Upload one or more images", "Select quality level (High, Medium, Low)", "Choose output format", "Click 'Compress' to process", "Download compressed images"], faqItems: [{ question: "What image formats are supported?", answer: "JPG, PNG, WebP, GIF, and other common formats are supported." }, { question: "Can I compress multiple images?", answer: "Yes, upload multiple images and they will be compressed individually." }, { question: "Is there a file size limit?", answer: "Single images up to 100MB can be compressed." }] },
      { id: "image-resizer", name: "Image Resizer", description: "Resize images to specific dimensions quickly and easily. Maintain aspect ratio automatically or set custom proportions.", icon: Image, category: "image", path: "/tools/image-resizer", benefits: ["Resize to exact pixel dimensions", "Maintain aspect ratio automatically", "Batch resize multiple images", "Preserve image quality", "No quality loss from resizing"], useCases: ["Create profile pictures and avatars", "Optimize images for social media", "Generate thumbnail previews", "Prepare images for responsive design"], howToUse: ["Upload your image", "Enter desired width and height", "Choose 'Maintain Aspect Ratio' if needed", "Preview the resized image", "Click 'Resize' to apply changes"], faqItems: [{ question: "What if I only specify width?", answer: "If 'Maintain Aspect Ratio' is checked, the height will adjust automatically." }, { question: "Can I resize without losing quality?", answer: "Yes, the tool uses advanced interpolation. Downscaling maintains excellent quality." }, { question: "Are there preset sizes?", answer: "Yes, common presets for profile pictures and social media are available." }] },
      { id: "format-converter", name: "Format Converter", description: "Convert images between different file formats instantly. Maintain quality during conversion with customizable compression settings.", icon: Shuffle, category: "image", path: "/tools/format-converter", benefits: ["Convert between 6+ image formats", "Maintain image quality", "Batch process multiple images", "Customize quality settings", "Instant local conversion"], useCases: ["Convert images to WebP for web optimization", "Convert to PNG for transparency", "Create images in multiple formats", "Batch convert entire image libraries"], howToUse: ["Upload image(s)", "Select target format", "Adjust quality settings", "Preview conversion", "Click 'Convert' to process"], faqItems: [{ question: "Which format should I use for web?", answer: "WebP offers best compression. PNG for transparency, JPG for photos." }, { question: "Can I convert JPG to PNG without quality loss?", answer: "Yes, though converting from lossy to lossless won't recover lost original data." }, { question: "Are all formats supported?", answer: "We support JPG, PNG, WebP, GIF, BMP, and TIFF." }] },
      { id: "color-picker", name: "Color Picker", description: "Extract and convert colors between different formats. HEX, RGB, HSL, HSV, and CMYK conversions with instant results.", icon: Palette, category: "image", path: "/tools/color-picker", benefits: ["Convert between multiple color formats", "Copy color codes instantly", "Visual color picker interface", "See complementary colors", "Check color contrast for accessibility"], useCases: ["Get color codes for web and design", "Check color accessibility contrast", "Generate color palettes", "Match colors across formats"], howToUse: ["Click color picker area to select", "Or enter a color value in HEX/RGB/HSL", "View all color format equivalents", "Click any format to copy", "Use scheme generator for palettes"], faqItems: [{ question: "What color formats are supported?", answer: "HEX, RGB, RGBA, HSL, HSLA, HSV, and CMYK are all supported." }, { question: "Can I check color contrast?", answer: "Yes, select two colors and calculate contrast ratios for accessibility." }, { question: "How accurate are conversions?", answer: "All conversions use standard color space mathematics and are precise." }] },
    ],
  },
  {
    id: "file",
    name: "File Tools",
    description: "Compress & bundle files effortlessly",
    icon: Archive,
    color: "from-blue-500 to-cyan-500",
    tools: [
      { id: "file-compressor", name: "File Compressor", description: "Compress files and folders into ZIP archives to save storage space. Reduce file sizes by 30-70% depending on file types.", icon: Archive, category: "file", path: "/tools/file-compressor", benefits: ["Reduce file sizes by 30-70%", "Create universal ZIP format", "Compress entire folder structures", "Fast compression in seconds", "No additional software needed"], useCases: ["Archive old projects and documents", "Prepare files for email sending", "Create backups of important files", "Share multiple files as archive"], howToUse: ["Drag files/folders or click 'Select Files'", "Add more files as needed", "Name your ZIP archive", "Click 'Compress' to create ZIP", "Download the compressed archive"], faqItems: [{ question: "What's the file size limit?", answer: "No strict limit, but typical compression works best for files under 2GB." }, { question: "Can I password protect the ZIP?", answer: "Standard compression doesn't include password protection in this version." }, { question: "Are folder structures preserved?", answer: "Yes, all folders and subfolders are preserved in the compressed archive." }] },
      { id: "file-merger", name: "File Merger", description: "Combine multiple text files into a single document. Consolidate log files, CSV data, or merge text-based documents.", icon: Merge, category: "file", path: "/tools/file-merger", benefits: ["Merge multiple text files instantly", "Maintain file order and structure", "Add custom separators between files", "Support for multiple text formats", "Preview before merging"], useCases: ["Combine server logs for analysis", "Merge CSV data from multiple sources", "Consolidate text reports", "Combine configuration files"], howToUse: ["Click 'Select Files' and choose text files", "Drag to arrange files in order", "Choose separator (newline, blank line, custom)", "Preview the merged result", "Click 'Merge' to combine"], faqItems: [{ question: "What file formats are supported?", answer: "TXT, CSV, LOG, JSON, and most text-based formats are supported." }, { question: "Can I undo a merge?", answer: "The tool shows a preview before merging, so you can verify before confirming." }, { question: "Is there a file size limit?", answer: "Combined files should total under 50MB for optimal performance." }] },
    ],
  },
  {
    id: "generator",
    name: "Generator Tools",
    description: "Generate QR codes, passwords, hashes & more",
    icon: QrCode,
    color: "from-purple-500 to-pink-500",
    tools: [
      { id: "qr-generator", name: "QR Code Generator", description: "Generate QR codes from text, URLs, or contact information instantly. Create high-quality QR codes for marketing, packaging, and events.", icon: QrCode, category: "generator", path: "/tools/qr-generator", benefits: ["Generate QR codes in seconds", "Support for text, URLs, contacts, WiFi", "Customizable size and colors", "Export as PNG or SVG", "Instantly scannable by any device"], useCases: ["Create QR codes for marketing campaigns", "Share contact information digitally", "Link physical products to digital content", "Generate WiFi sharing codes"], howToUse: ["Enter text or URL to encode", "Select QR code size", "Choose error correction level", "Preview the QR code", "Click 'Download' to save"], faqItems: [{ question: "Can I customize QR code colors?", answer: "Yes, customize foreground and background colors for branding." }, { question: "What's the maximum data I can encode?", answer: "Up to 2953 bytes depending on error correction level." }, { question: "Which QR formats are supported?", answer: "Standard QR codes, vCard for contacts, and URLs are all supported." }] },
      { id: "password-generator", name: "Password Generator", description: "Generate strong, random passwords to enhance your online security. Cryptographically secure with customizable character sets.", icon: Lock, category: "generator", path: "/tools/password-generator", benefits: ["Generate cryptographically secure passwords", "Customize character sets and length", "Instant strength analysis", "Batch generate multiple passwords", "Copy instantly to clipboard"], useCases: ["Create unique passwords for every account", "Generate API keys and tokens", "Create security credentials for systems", "Batch generate user account passwords"], howToUse: ["Set desired password length (minimum 8)", "Check boxes for character types", "Click 'Generate Password'", "Review password strength", "Click 'Copy' to save"], faqItems: [{ question: "How secure are these passwords?", answer: "Passwords use cryptographically secure random generation directly in your browser." }, { question: "Can I save generated passwords?", answer: "Passwords are shown but not stored. Use a password manager for secure storage." }, { question: "What's the recommended password length?", answer: "12+ for general accounts, 16+ for high-security systems." }] },
      { id: "hash-generator", name: "Hash Generator", description: "Generate cryptographic hashes for text, files, and data verification. Support for MD5, SHA-1, SHA-256, SHA-512 and more.", icon: Hash, category: "generator", path: "/tools/hash-generator", benefits: ["Generate multiple hash formats", "Verify file integrity instantly", "Hash text or files", "Support for modern hash algorithms", "Local processing for security"], useCases: ["Generate file checksums for distribution", "Verify file downloads haven't been corrupted", "Create digital fingerprints", "Generate password hashes"], howToUse: ["Enter text or upload a file", "Select hashing algorithm", "Click 'Generate' to create hash", "View hash and other algorithms", "Copy hash for sharing"], faqItems: [{ question: "Which hash algorithm should I use?", answer: "SHA-256 is recommended for modern applications. SHA-512 for maximum security." }, { question: "Can I verify if a file is authentic?", answer: "Yes, if you have the original hash, compare with your current file hash." }, { question: "Is this suitable for password hashing?", answer: "For learning purposes yes. In production, use dedicated libraries with salting." }] },
      { id: "lorem-generator", name: "Lorem Ipsum Generator", description: "Generate placeholder text for design mockups and web development. Create Lorem Ipsum text in customizable quantities.", icon: AlignLeft, category: "generator", path: "/tools/lorem-generator", benefits: ["Generate unlimited placeholder text", "Customize quantity (words, sentences, paragraphs)", "Copy instantly to clipboard", "Multiple language support", "Perfect for mockups and prototypes"], useCases: ["Fill design mockups with realistic text", "Test typography and layout variations", "Create content placeholders for sites", "Generate dummy data for forms"], howToUse: ["Choose text unit (words, sentences, paragraphs)", "Enter quantity needed", "Click 'Generate' to create Lorem text", "Preview generated text", "Click 'Copy' to save"], faqItems: [{ question: "Why use Lorem Ipsum instead of real text?", answer: "Placeholder text focuses review on design rather than content. Standard for mockups." }, { question: "Can I generate other languages?", answer: "Yes, alternative placeholder generators for various languages are available." }, { question: "Is this text copyrighted?", answer: "Lorem Ipsum is public domain placeholder text. Safe to use in any project." }] },
    ],
  },
  {
    id: "text",
    name: "Text Tools",
    description: "Count, convert, encode & transform text",
    icon: Type,
    color: "from-yellow-500 to-amber-500",
    tools: [
      { id: "word-counter", name: "Word Counter", description: "Count words, characters, sentences, and paragraphs instantly. Get detailed text analysis including reading time estimation.", icon: Type, category: "text", path: "/tools/word-counter", benefits: ["Instant word and character counting", "Track reading time automatically", "Count multiple text metrics", "Estimate reading level", "No character limits"], useCases: ["Meet essay and assignment word requirements", "Track blog post length during writing", "Analyze document statistics", "Estimate reading time for content"], howToUse: ["Paste or type text into the area", "View instant word count", "Check reading time estimate", "Review detailed statistics", "Copy results if needed"], faqItems: [{ question: "How is reading time calculated?", answer: "Reading time uses average adult reading speed of ~200 words per minute." }, { question: "Does punctuation count as characters?", answer: "Yes, all characters including punctuation are counted." }, { question: "Can I analyze large documents?", answer: "Yes, the tool can handle hundreds of thousands of words." }] },
      { id: "case-converter", name: "Case Converter", description: "Convert text between different case formats instantly. UPPERCASE, lowercase, Title Case, camelCase, snake_case and more.", icon: CaseSensitive, category: "text", path: "/tools/case-converter", benefits: ["Convert between 8+ case formats", "Instant real-time conversion", "Perfect for code formatting", "Handle punctuation intelligently", "Copy results to clipboard"], useCases: ["Format variable names for code", "Convert titles and headings", "Prepare text for different systems", "Quick case-to-case conversion"], howToUse: ["Paste or type text", "Select desired case format", "View instant conversion", "Select converted version", "Click 'Copy' to save"], faqItems: [{ question: "What case formats are supported?", answer: "UPPERCASE, lowercase, Title Case, camelCase, PascalCase, snake_case, kebab-case, and more." }, { question: "Can I convert multiple paragraphs?", answer: "Yes, the tool processes entire documents." }, { question: "How are spaces handled?", answer: "Each format handles spaces according to its rules: snake_case uses underscores, camelCase removes spaces." }] },
      { id: "base64", name: "Base64 Encoder/Decoder", description: "Encode and decode text and files using Base64 format. Perfect for APIs, emails, and data transmission.", icon: Binary, category: "text", path: "/tools/base64", benefits: ["Encode/decode instantly", "Support for text and files", "Create data URIs for images", "Useful for API development", "No file size limits"], useCases: ["Encode credentials for API authentication", "Create data URIs for embedding images", "Transmit binary data safely", "Prepare files for email"], howToUse: ["Paste text or upload file", "Click 'Encode' or 'Decode'", "View result instantly", "Copy encoded text or download", "Use in your application"], faqItems: [{ question: "What is Base64 used for?", answer: "Base64 converts binary data to text format for safe transmission through text-only systems." }, { question: "Can I encode images?", answer: "Yes, upload images and create Base64 data URIs for embedding." }, { question: "Is Base64 secure for passwords?", answer: "Base64 is encoding, not encryption. Never use for sensitive data without actual encryption." }] },
      { id: "json-formatter", name: "JSON Formatter", description: "Format, validate, and minify JSON data instantly. Perfect for debugging API responses and configuration files.", icon: FileCode, category: "text", path: "/tools/json-formatter", benefits: ["Validate JSON syntax instantly", "Format with proper indentation", "Minify for size reduction", "Detect errors with location info", "Convert to/from minified"], useCases: ["Debug API JSON responses", "Validate JSON configuration files", "Minify JSON for production", "Beautiful print JSON data"], howToUse: ["Paste JSON into editor", "Choose 'Format' or 'Minify'", "View formatted result", "Errors highlighted with location", "Copy processed JSON"], faqItems: [{ question: "What error messages will I see?", answer: "Specific errors with line and column numbers for quick debugging." }, { question: "Can I both format and minify?", answer: "Yes, format to readable or minify to compact version." }, { question: "Is there a file size limit?", answer: "The tool handles files up to 50MB." }] },
      { id: "text-diff", name: "Text Diff", description: "Compare two texts and see differences highlighted side by side. Color-coded additions, deletions, and modifications.", icon: LetterText, category: "text", path: "/tools/text-diff", benefits: ["See text changes instantly", "Color-coded additions and deletions", "Side-by-side comparison view", "Character-level difference detection", "Perfect for code review"], useCases: ["Compare document versions", "Review code changes in pull requests", "Verify changes before saving", "Audit configuration file modifications"], howToUse: ["Paste original text in left panel", "Paste modified text in right panel", "Tool highlights differences", "Review color-coded changes", "Copy comparison if needed"], faqItems: [{ question: "Can I compare large files?", answer: "Yes, the tool handles large documents efficiently." }, { question: "What if only formatting changed?", answer: "The tool shows all changes including whitespace differences." }, { question: "Can I export the diff?", answer: "Yes, copy comparison or export in unified diff format." }] },
      { id: "font-changer", name: "Font Changer", description: "Convert text to different Unicode font styles. Bold, italic, monospace, decorative fonts and more for social media and messaging.", icon: PenTool, category: "text", path: "/tools/font-changer", benefits: ["Create 20+ text style variations", "Perfect for social media posts", "Instant preview of all styles", "Copy styled text with one click", "Support for creative formatting"], useCases: ["Make social media posts stand out", "Create styled text for messages", "Generate creative text variations", "Format text for special emphasis"], howToUse: ["Type or paste text to style", "View previews of all font styles", "Click on a style you like", "Text is copied to clipboard", "Paste into social media"], faqItems: [{ question: "Will styled text work everywhere?", answer: "Most platforms support Unicode fonts. Some older systems may not display correctly." }, { question: "How many styles are available?", answer: "20+ font style variations including bold, italic, script, fraktur, and decorative styles." }, { question: "Can I use this for professional documents?", answer: "While technically possible, use standard fonts for professional documents." }] },
    ],
  },
  {
    id: "share",
    name: "Share Tools",
    description: "Share text & files with unique links",
    icon: Share2,
    color: "from-indigo-500 to-violet-500",
    tools: [
      { id: "text-share", name: "Text Share", description: "Share text instantly without paste services. Encodes text into shareable URL links with complete privacy.", icon: Share2, category: "share", path: "/tools/text-share", benefits: ["Share text instantly via URL", "No server storage of data", "Complete privacy", "Generate QR codes for sharing", "Easy to use interface"], useCases: ["Share code snippets quickly", "Send temporary messages", "Share configuration snippets", "Quick knowledge sharing"], howToUse: ["Paste text you want to share", "Click 'Generate Share Link'", "Copy the generated URL", "Share URL with anyone", "They click link to view text"], faqItems: [{ question: "How long does a share link last?", answer: "Links work as long as the browser session is active. They use URL encoding with no server storage." }, { question: "Is my shared text private?", answer: "Yes, text is encoded in the URL. Only people with the link can see it." }, { question: "Can I delete a share?", answer: "Links exist as long as you don't delete the URL yourself." }] },
    ],
  },
  {
    id: "utility",
    name: "Utility Tools",
    description: "Handy everyday utilities",
    icon: Zap,
    color: "from-teal-500 to-sky-500",
    tools: [
      { id: "timestamp-converter", name: "Timestamp Converter", description: "Convert Unix timestamps to human-readable dates and vice versa instantly. Handle both millisecond and second timestamps.", icon: Clock, category: "utility", path: "/tools/timestamp-converter", benefits: ["Convert timestamps instantly", "Support for multiple formats", "Timezone-aware conversions", "Multiple output formats", "Perfect for log debugging"], useCases: ["Debug application logs with timestamps", "Convert API response timestamps", "Understand Unix timestamp values", "Generate timestamps for APIs"], howToUse: ["Enter Unix timestamp or click 'Current Time'", "View instant conversion", "Adjust timezone if needed", "Or enter date/time to get timestamp", "Copy results to clipboard"], faqItems: [{ question: "What's the difference between milliseconds and seconds?", answer: "Unix timestamps in seconds are standard. Milliseconds add 3 digits for sub-second precision." }, { question: "How do timezone conversions work?", answer: "The tool uses your browser's timezone. You can manually select different timezones." }, { question: "Can I convert future dates?", answer: "Yes, any date can be converted to Unix timestamp, including future dates." }] },
      { id: "unit-converter", name: "Unit Converter", description: "Convert between different units of measurement instantly. Length, weight, temperature, volume, speed and more.", icon: Calculator, category: "utility", path: "/tools/unit-converter", benefits: ["Convert between 50+ unit types", "Instant real-time conversion", "Support metric and imperial", "High precision calculations", "Perfect for international work"], useCases: ["Convert between metric and imperial", "Calculate cooking measurements", "Convert speeds and distances", "Science and physics calculations"], howToUse: ["Select unit category", "Enter value to convert", "Select source and target units", "View instant result", "Copy result if needed"], faqItems: [{ question: "What unit categories are supported?", answer: "Length, weight, volume, temperature, speed, area, pressure, and energy conversions." }, { question: "How accurate are conversions?", answer: "Conversions use standard international conversion factors with precision." }, { question: "Can I convert temperature?", answer: "Yes, Celsius, Fahrenheit, and Kelvin conversions are fully supported." }] },
      { id: "url-encoder", name: "URL Encoder/Decoder", description: "Encode and decode URLs and special characters instantly. Essential for web development and API work.", icon: Globe, category: "utility", path: "/tools/url-encoder", benefits: ["Encode text for URL safety", "Decode percent-encoded URLs", "Handle international characters", "Real-time conversion", "Essential for web development"], useCases: ["Encode text for URL query parameters", "Decode API response URLs", "Fix broken URLs with special characters", "Prepare data for URL transmission"], howToUse: ["Paste text or URL", "Click 'Encode' or 'Decode'", "View instant conversion", "Review result", "Copy encoded/decoded result"], faqItems: [{ question: "When do I need URL encoding?", answer: "When passing special characters or spaces as URL parameters, or building URLs programmatically." }, { question: "What characters get encoded?", answer: "Spaces become %20, special characters become % followed by hex codes." }, { question: "Is URL encoding encryption?", answer: "No, URL encoding is for safe transmission, not encryption. Not secure for sensitive data." }] },
    ],
  },
];

export const allTools = categories.flatMap((c) => c.tools);

export function getToolById(id: string) {
  return allTools.find((t) => t.id === id);
}

export function getCategoryByToolId(id: string) {
  return categories.find((c) => c.tools.some((t) => t.id === id));
}

export function getRelatedTools(toolId: string, limit = 4) {
  const tool = getToolById(toolId);
  if (!tool) return allTools.slice(0, limit);
  const sameCat = allTools.filter((t) => t.category === tool.category && t.id !== toolId);
  const others = allTools.filter((t) => t.category !== tool.category);
  return [...sameCat, ...others].slice(0, limit);
}
